AWSTemplateFormatVersion: '2010-09-09'
Description: Serverless Frontend CI/CD.
Resources:
  index-photo:
    Type: AWS::Serverless::Function
    Properties:
      Description: LambdaFunction1
      Handler: index-photos.lambda_handler
      Runtime: python3.7
      CodeUri: ./index-photos
      FunctionName: "index-photos"
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::857213095760:role/service-role/index-photos-LF1'
      Events:
        S3BucketEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: hw2bucket2
            Events:
              - 's3:ObjectCreated:Put'



